# Generated by Django 4.2.29 on 2026-04-06 11:51

import Ticket.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multi_email_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('email', multi_email_field.fields.MultiEmailField(blank=True, default=[], null=True)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='files/desarrollos/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('file2', models.FileField(blank=True, null=True, upload_to='files/desarrollos/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('file3', models.FileField(blank=True, null=True, upload_to='files/desarrollos/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('estado', models.BooleanField(default=True)),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Login.programador')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Login.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=500)),
                ('email', multi_email_field.fields.MultiEmailField(blank=True, default=[], null=True)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_update', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='files/tickets/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('file2', models.FileField(blank=True, null=True, upload_to='files/tickets/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('file3', models.FileField(blank=True, null=True, upload_to='files/tickets/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('estado', models.BooleanField(default=True)),
                ('register_estado', models.BooleanField(default=True)),
                ('edit_register', models.BooleanField(default=False)),
                ('attend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Login.programador')),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ticket.modulos')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['id'],
                'permissions': [('admin', 'Puede Administrar los ticket (ver historial, dar de baja)'), ('attend', 'Puede Atender un ticket'), ('register', 'Puede Registrar un nuevo ticket')],
            },
        ),
        migrations.CreateModel(
            name='RegistroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('msg', models.CharField(max_length=500)),
                ('file1', models.FileField(blank=True, null=True, upload_to='files/registros_de_trabajos/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('file2', models.FileField(blank=True, null=True, upload_to='files/registros_de_trabajos/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('programmer', models.BooleanField(default=False)),
                ('desarrollo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.desarrollo')),
                ('register_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creacion', models.DateTimeField(blank=True, null=True)),
                ('msg', models.CharField(max_length=500)),
                ('file1', models.FileField(blank=True, null=True, upload_to='files/ticket_history/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('file2', models.FileField(blank=True, null=True, upload_to='files/ticket_history/%Y%m%d/', validators=[Ticket.validators.FileSize])),
                ('tiempo', models.TimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('programmer', models.BooleanField(default=False)),
                ('register_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ticket.tickets')),
            ],
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Ticket.modulos'),
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
