#!/bin/bash 
### BEGIN Copyright
# Copyright 2024, Jesus Emanuel Luccioni
# All rights reserved.
#
# This file is part of devops for Open Container (in this case docker ), config and setting
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SCRIPT IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SCRIPT, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
##
### END   Copyright
#
## set var for check import file
__docker_config__=1

### BEGIN setting GLOBAL VARs 
## container and image (lower case) names
CONTAINER_NAME='ClientApisRest'
IMGAGE_NAME='client-apis-rest'

IP=127.0.0.1
PORT=8080




##
DOCKERFOLDER='0D-Dockerfiles'
DOCKERFILE="Dockerfile"
DOCKERIMAGE="jeluccioni/${IMGAGE_NAME}"
DOCKERCONTAINER="${CONTAINER_NAME}"
DOCKERCMD='/bin/bash'
### set flag, with mount volumen over current folder in host
## para docker container tenga acceso al localhost
#DOCKERFLAGS="-it -v $PWD/:/home/user:rw"
# --add-host host.docker.internal:host-gateway
# --network="host"
#DOCKERFLAGS="-it -v $PWD/:/home/user:rw --add-host host.docker.internal:host-gateway"
#DOCKERFLAGS="-it -v $PWD/:/home/user:rw --network=host --add-host host.docker.internal:host-gateway"
DOCKERFLAGS="-it -v $PWD/:/home/user:rw --network=host -P"


### END   setting GLOBAL VARs


### BEGIN function config
## function for init in target --dk-build
function dck_cfg_dk_build_ini()
{
  # Necesario para incializacion de OPEN GL
  return 0
}

function dck_cfg_dk_test()
{
  # Necesario para incializacion de OPEN GL  
  return 0
}
### END   function config
