# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
#import protobuf.pipeline_process_pb2 as pipeline__process__pb2
import pipeline_process_pb2 as pipeline__process__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pipeline_process_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CreateStub(object):
    """1. Enviar documento a procesa
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create = channel.unary_unary(
                '/Create/create',
                request_serializer=pipeline__process__pb2.CreateRequest.SerializeToString,
                response_deserializer=pipeline__process__pb2.CreateResponse.FromString,
                _registered_method=True)


class CreateServicer(object):
    """1. Enviar documento a procesa
    """

    def create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create': grpc.unary_unary_rpc_method_handler(
                    servicer.create,
                    request_deserializer=pipeline__process__pb2.CreateRequest.FromString,
                    response_serializer=pipeline__process__pb2.CreateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Create', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Create', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Create(object):
    """1. Enviar documento a procesa
    """

    @staticmethod
    def create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Create/create',
            pipeline__process__pb2.CreateRequest.SerializeToString,
            pipeline__process__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GetStub(object):
    """2. Consultar estado de un Job
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/Get/get',
                request_serializer=pipeline__process__pb2.GetRequest.SerializeToString,
                response_deserializer=pipeline__process__pb2.GetResponse.FromString,
                _registered_method=True)


class GetServicer(object):
    """2. Consultar estado de un Job
    """

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=pipeline__process__pb2.GetRequest.FromString,
                    response_serializer=pipeline__process__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Get', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Get', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Get(object):
    """2. Consultar estado de un Job
    """

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Get/get',
            pipeline__process__pb2.GetRequest.SerializeToString,
            pipeline__process__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PutStub(object):
    """3. Modificar un Job
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.put = channel.unary_unary(
                '/Put/put',
                request_serializer=pipeline__process__pb2.PutRequest.SerializeToString,
                response_deserializer=pipeline__process__pb2.PutResponse.FromString,
                _registered_method=True)


class PutServicer(object):
    """3. Modificar un Job
    """

    def put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PutServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'put': grpc.unary_unary_rpc_method_handler(
                    servicer.put,
                    request_deserializer=pipeline__process__pb2.PutRequest.FromString,
                    response_serializer=pipeline__process__pb2.PutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Put', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Put', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Put(object):
    """3. Modificar un Job
    """

    @staticmethod
    def put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Put/put',
            pipeline__process__pb2.PutRequest.SerializeToString,
            pipeline__process__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ListJobsStub(object):
    """4. Listar un Job
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_jobs = channel.unary_unary(
                '/ListJobs/list_jobs',
                request_serializer=pipeline__process__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=pipeline__process__pb2.ListJobsResponse.FromString,
                _registered_method=True)


class ListJobsServicer(object):
    """4. Listar un Job
    """

    def list_jobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListJobsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_jobs': grpc.unary_unary_rpc_method_handler(
                    servicer.list_jobs,
                    request_deserializer=pipeline__process__pb2.ListJobsRequest.FromString,
                    response_serializer=pipeline__process__pb2.ListJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListJobs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListJobs', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListJobs(object):
    """4. Listar un Job
    """

    @staticmethod
    def list_jobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListJobs/list_jobs',
            pipeline__process__pb2.ListJobsRequest.SerializeToString,
            pipeline__process__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ListProvidersStub(object):
    """5. Listado de Proveedores 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_providers = channel.unary_unary(
                '/ListProviders/list_providers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pipeline__process__pb2.ListProvidersResponse.FromString,
                _registered_method=True)


class ListProvidersServicer(object):
    """5. Listado de Proveedores 
    """

    def list_providers(self, request, context):
        """Method with no request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListProvidersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_providers': grpc.unary_unary_rpc_method_handler(
                    servicer.list_providers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pipeline__process__pb2.ListProvidersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ListProviders', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ListProviders', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListProviders(object):
    """5. Listado de Proveedores 
    """

    @staticmethod
    def list_providers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ListProviders/list_providers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pipeline__process__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
