"""
Django settings for ticketsys project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from collections import namedtuple

DEBUG = True
''' SECURITY WARNING: don't run with debug turned on in production! 
python3 manage.py runserver 0.0.0.0:8000 --insecure
'''


DATA_BASE_TYPE:str = 'sqlite'
''' set data base type
    'sqlite' 
    'postgres'
'''

AUTH_USER_MODEL:str = 'Login.User'
''' Build paths inside the project like 
    this: BASE_DIR / 'subdir'.
'''

BASE_DIR:Path = Path(__file__).resolve().parent.parent
''' base dir for project '''


DEFAULT_ROOT_DIRS_EMPTY:tuple[str] = (
    'logs',          # custom logs
    'staticfiles',   # html templates, css and JavaScripts files 
)

for folder in DEFAULT_ROOT_DIRS_EMPTY:
    root_dir = os.path.join(BASE_DIR, folder)
    if not os.path.exists(root_dir):
        os.makedirs(root_dir)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'ticketsys.log'),
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False, # disable log/app.log
        },
    },
}



# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z5b_#-m*5mk-eip+td7ub38b4mc=abfjiff%&^376x07d4i9np'
# ALLOWED_HOSTS = ['192.168.0.240','127.0.0.1','0.0.0.0']
ALLOWED_HOSTS = ['127.0.0.1','0.0.0.0','192.168.0.225']
CORS_REPLACE_HTTPS_REFERER      = False
HOST_SCHEME                     = "http://"
SECURE_PROXY_SSL_HEADER         = None
SECURE_SSL_REDIRECT             = False
SESSION_COOKIE_SECURE           = False
CSRF_COOKIE_SECURE              = False
SECURE_HSTS_SECONDS             = None
SECURE_HSTS_INCLUDE_SUBDOMAINS  = False
SECURE_FRAME_DENY               = False


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'psycopg2',
    #'bootstrap5',       # pip install django-bootstrap5
    'bootstrap5',        # pip install django-bootstrap-v5    
    'multi_email_field', # pip install django-multi-email-field
    'easy_thumbnails',
    'filer',             # pip install django-filer [from filer.fields.file import FilerFileField]
    'mptt',              # pip install django-mptt
                         # pip install pillow -> para manejo de imagenes
    'xlsxwriter',        # pip install XlsxWriter
    ## 
    ## Modulos, desarrollados/creados
    'Login',
    'registerticket',
    'attendticket',
    'Ticket',    
    'Buttons',
    'administrator'
]


MIDDLEWARE = [ 
    ##  MIDDLEWARE  'django.contrib.sessions.middleware.SessionMiddleware'
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'Login/templates',
            'attendticket/templates',
            'registerticket/templates',
            'Ticket/templates',
            'Buttons/templates',
            'Desarrollos/templates',
            'administrator/templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'config.wsgi.application'


# Database settings
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
      'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
      'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
      'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
      'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE:str = 'es-ar'
TIME_ZONE:str = 'America/Argentina/Buenos_Aires'
USE_I18N:bool = True
USE_L10N:bool = True
USE_TZ:bool = False



STATIC_URL:str = '/static/'
STATIC_ROOT:Path = BASE_DIR / 'staticfiles/'
MEDIA_ROOT:Path = BASE_DIR /'media/'
MEDIA_URL:str = '/media/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
Nombre de servidor: smtp.office365.com
Puerto: 587
Método de cifrado: STARTTLS
"""
EMAIL_HOST:str = "smtp.office365.com"
EMAIL_USE_TLS:bool = True
EMAIL_PORT:int = 587



EMAIL_HOST_USER:str = ''
# EMAIL_HOST_PASSWORD = 'r0b0tt1ck3t5y5' OLD
EMAIL_HOST_PASSWORD:str = ''


## lista de Email de administradores
EMAIL_REPLY_TO:str = 'piero.jel@gmail.com'
EMAIL_SEND_RETRY:int = 5

if  ALLOWED_HOSTS[1] == '127.0.0.1' :
    HOSTING_URL = f'http://{ALLOWED_HOSTS[1]}:8000'
else:
    HOSTING_URL = f'http://{ALLOWED_HOSTS[1]}'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


## defines para normalizar los formularios
FormatForm = namedtuple('FormatForm',[ 'username','firstname','lastname','email',
                                       'telephone','comment','company_name',
                                       'company_tel1','company_tel2'])

FORM_TITLE:FormatForm = FormatForm(
    'Ingrese el nombre de Usuario',
    'Ingrese Su primer Nombre',
    'Ingrese Su Apellido',
    'Ingrese Su Dirección de Correo Electronico',
    'Ingrese Su Numero de Telefono',
    'Ingrese un comentario de hasta 500 caracteres',
    'Ingrese el Nombre de la Empresa',
    'Ingrese el número de teléfono principal',
    'Ingrese un número de teléfono secundario'
)

FORM_PLACEHOLDER:FormatForm = FormatForm(
    'user name',
    'firts name',
    'last name',
    'name@example.com',
    '+COD XXX-XXX-XXX',
    'comment of to 500 characters',
    'Company Name',
    'main phone number',
    'secondary phone number'
)





#PHONE_NUMBER_PATTERN:str = r"^(\+\d{1,3})?[\s.-]?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$"
PHONE_NUMBER_PATTERN:str = r"^\+?\d{1,3}?[\s.-]?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$"

