# Generated by Django 5.2.1 on 2025-05-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('nickname', models.CharField(max_length=256)),
                ('seller_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('price', models.FloatField(default=0.0)),
                ('thumbnail', models.CharField(max_length=256)),
                ('listing_type_id', models.CharField(max_length=32)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.seller')),
            ],
        ),
    ]
