# Generated by Django 5.2.1 on 2025-05-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_id',
            new_name='id',
        ),
    ]
