# Generated by Django 5.2.1 on 2025-05-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_seller_id_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
    ]
