## enable/disable  bash debug
BASH_DEBUG=false

## setting multi-services {app|ddbb|nginx|all}
SERVICES_MUL_APP=false

## Nombre del archivo yml p/docker compose
COMPOSE_FILE=docker-compose-dev.yml

## Nombre de cada contenedor
CONTAINER_APP=RTWebApp
CONTAINER_DDBB=RTdatabase
CONTAINER_NGINX=RDNginx

## Nombre de cada servicio dado de alta en el compose
SERVICE_APP=rd_django
SERVICE_DDBB=rd_postgres
SERVICE_NGINX=rd_nginx

## entry point p/c contenedor
ENTRYPOINT_APP='bash'
#ENTRYPOINT_DDBB="psql -U ${POSTGRES_USER}"
ENTRYPOINT_DDBB='bash'


URL_LOCAL_HOME='http://localhost:8080'
